---
- name: configure web servers
  hosts: all
  become: true
  tasks: 
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present
    - name: eneable service
      service:
        name: apache2
        enable: yes
        state: present
